Repository IF-TG/iOS, pull requests merged in 2023-09, with the labels that each got.

#35 Feature/feed userpostsearch
  travelPlan/Source/Common/Extension/UIColor+AppPalette.swift
  travelPlan/Source/Common/Utils/Calculator/CoreTextSizeCalculator.swift
  travelPlan/Source/Common/ViewController/CautionAlertViewController.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/CollectionReusableView/PostRecommendationSearchHeaderView+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/CollectionReusableView/PostSearchFooterView+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/CollectionReusableView/PostSearchHeaderView+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/DefaultPostSearchLayout+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/LeftAlignedCollectionViewFlowLayout+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/PostSearchTagCell+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/PostSearchTagLabel+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/PostSearchViewModel+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/TagCell/PostRecentSearchTagCell+Constants.swift
  travelPlan/Source/Feature/Feed/Constant/PostSearch/TagCell/PostRecommendationSearchTagCell+Constants.swift
  travelPlan/Source/Feature/Feed/Extension/PostSearchViewModel+Associatedtype.swift
  travelPlan/Source/Feature/Feed/Model/PostSearchModel.swift
  travelPlan/Source/Feature/Feed/Model/PostSearchSectionItemModel.swift
  travelPlan/Source/Feature/Feed/Protocol/PostSearch/PostRecentSearchTagCellDelegate.swift
  travelPlan/Source/Feature/Feed/Protocol/PostSearch/PostSearchCollectionViewDataSource.swift
  travelPlan/Source/Feature/Feed/Protocol/PostSearch/PostSearchCollectionViewDelegate.swift
  travelPlan/Source/Feature/Feed/Protocol/PostSearch/PostSearchHeaderViewDelegate.swift
  travelPlan/Source/Feature/Feed/Protocol/PostSearch/PostSearchLayout.swift
  travelPlan/Source/Feature/Feed/Protocol/PostSearchTagCellDelegate.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/DefaultPostSearchLayout.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/LeftAlignedCollectionViewFlowLayout.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/PostSearchCollectionViewManager.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/PostSearchHeaderView.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/PostSearchTagCell.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/PostSearchTagLabel.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/TagCell/PostRecentSearchHeaderView.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/TagCell/PostRecentSearchTagCell.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/TagCell/PostRecommendationSearchHeaderView.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/TagCell/PostRecommendationSearchTagCell.swift
  travelPlan/Source/Feature/Feed/View/PostSearch/TagCell/PostSearchFooterView.swift
  travelPlan/Source/Feature/Feed/ViewController/PostSearchViewController.swift
  travelPlan/Source/Feature/Feed/ViewModel/PostSearchViewModel.swift
  travelPlan/Source/Feature/Search/Constants/DefaultSearchLayout+Constants.swift
  travelPlan/Source/Feature/Search/Constants/SearchFamousSpotCell+Constants.swift
  travelPlan/Source/Feature/Search/Constants/SearchHeaderView+Constants.swift
  travelPlan/Source/Feature/Search/Constants/SearchViewController+Constants.swift
  travelPlan/Source/Feature/Search/Model/SearchFamousSpotModel.swift
  travelPlan/Source/Feature/Search/View/SearchFamousSpotCell.swift
  travelPlan/Source/Feature/Search/View/SearchHeaderView.swift
  travelPlan/Source/Feature/Search/View/SearchLayout.swift
  travelPlan/Source/Feature/Search/ViewController/SearchViewController.swift
  travelPlan/Source/Support/Assets.xcassets/buttonIcon/cancel.imageset/Contents.json
  travelPlan/Source/Support/Assets.xcassets/buttonIcon/cancel.imageset/cancel.png
  travelPlan/Source/Support/Assets.xcassets/buttonIcon/cancel.imageset/cancel@2x.png
  travelPlan/Source/Support/Assets.xcassets/buttonIcon/cancel.imageset/cancel@3x.png
  travelPlan/travelPlan.xcodeproj/project.pbxproj
Labels: ✨ Enhancement, 💡 Feature, 🖥 View, 👨‍💻 ViewModel, 🏖 Common, 🎨 Style, 📲 ViewController, 🗑 Remove, ✨ Refactor, 🍒 Issue

#36 [Feature] base bottom sheet를 구현했습니다.
  travelPlan/Source/Common/Extension/UIViewController.swift
  travelPlan/Source/Common/View/BottomSheetView.swift
  travelPlan/Source/Common/ViewController/BaseBottomSheetViewController.swift
  travelPlan/travelPlan.xcodeproj/project.pbxproj
Labels: 💡 Feature, 🖥 View, 🏖 Common, 📲 ViewController

#37 Feature/update sh coordinator
  travelPlan/Source/Feature/ApplicationCoordinator.swift
  travelPlan/Source/Feature/Authentication/Login/Coordinator/LoginCoordinator.swift
  travelPlan/Source/Feature/Authentication/Login/ViewController/LoginViewController.swift
  travelPlan/Source/Feature/Favorite/FavoriteList/Coordinator/FavoriteCoordinator.swift
  travelPlan/Source/Feature/Favorite/FavoriteList/ViewController/FavoriteViewController.swift
  travelPlan/Source/Feature/Feed/Coordinator/FeedCoordinator.swift
  travelPlan/Source/Feature/Feed/Coordinator/PostSearchCoordiantor.swift
  travelPlan/Source/Feature/Feed/ViewController/FeedViewController.swift
  travelPlan/Source/Feature/Feed/ViewController/PostSearchViewController.swift
  travelPlan/Source/Feature/Main/Coordinator/MainCoordinator.swift
  travelPlan/Source/Feature/Plan/Coordinator/PlanCoordinator.swift
  travelPlan/Source/Feature/Plan/ViewController/PlanViewController.swift
  travelPlan/Source/Feature/Profile/Coordinator/ProfileCoordinator.swift
  travelPlan/Source/Feature/Profile/ViewController/ProfileViewController.swift
  travelPlan/Source/Feature/Search/Coordinator/SearchCoordinator.swift
  travelPlan/Source/Feature/Search/ViewController/SearchViewController.swift
  travelPlan/travelPlan.xcodeproj/project.pbxproj
  travelPlan/travelPlan.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 🏖 Common, 📲 ViewController, ✨ Refactor, 🐾 Coordinator

#47 [Hotfix] 깃허브 projet 이슈 item 템플릿 추가했습니다.
  .github/ISSUE_TEMPLATE/todo-item.md
Labels: 😅 Hotfix, 🏖 Common

#49 [Hotfix] GitHub project에 사용되는 todo item issue template 수정
  .github/ISSUE_TEMPLATE/todo-item.md
Labels: 😅 Hotfix

#48 [Hotfix] todo item issue template 업데이트
  .github/ISSUE_TEMPLATE/todo-item.md
Labels: 😅 Hotfix

#88 [Hotfix] 깃허브 이슈 템플릿 연동하기 위한 추가 반영했습니다.
  .github/ISSUE_TEMPLATE/todo-item.md
Labels: 😅 Hotfix

#89 [Hotfix] GitHub issue template 연동
  .github/ISSUE_TEMPLATE/todo-item.md
Labels: 😅 Hotfix
