Repository IF-TG/iOS, pull requests merged in 2024-10, with the labels that each got.

#289 [Docs] 리뷰작성 gif 추가
  README.md
Labels: 📜 Documentation

#287 [Dosc] 오타 수정
  README.md
Labels: 📜 Documentation

#290 [Rebuild] 로그인 화면 리빌딩
  travelPlan/Source/Application/DIContainer/AppDIContainer.swift
  travelPlan/Source/Core/Assembly/CoreAssembly.swift
  travelPlan/Source/Data/Assembly/SpringServerRepositoryAssembly.swift
  travelPlan/Source/Presentation/Assembly/PresentationAssembly.swift
  travelPlan/Source/Presentation/Login/Coordinator/LoginCoordinator.swift
  travelPlan/Source/Presentation/Login/Protocol/LoginViewModel.swift
  travelPlan/Source/Presentation/Login/ViewController/LoginViewController.swift
  travelPlan/Source/Presentation/Login/ViewModel/DefaultLoginViewModel.swift
  travelPlan/travelPlan.xcodeproj/project.pbxproj
Labels: ✨ Rebuild, 🐾 Coordinator, 🧶 DI Container

#291 [Fix] 검색기록화면의 검색 태그 삭제 시 오류발생 해결
  travelPlan/Source/Application/DIContainer/AppDIContainer.swift
  travelPlan/Source/Domain/Entities/Photo/PhotoEntity.swift
  travelPlan/Source/Domain/UseCases/Album/DefaultAlbumUseCase.swift
  travelPlan/Source/Presentation/Album/ViewController/AlbumViewController.swift
  travelPlan/Source/Presentation/Assembly/FlowCoordinatorAssembly.swift
  travelPlan/Source/Presentation/Feed/ViewModel/SearchHistoryViewModel.swift
  travelPlan/Source/Presentation/Main/Coordinator/MainCoordinator.swift
  travelPlan/Source/Presentation/Main/Model/TabBarCase.swift
  travelPlan/Source/Presentation/Main/ViewController/MainTabBarController.swift
  travelPlan/Source/Presentation/Plan/Coordinator/PlanCoordinator.swift
  travelPlan/Source/Presentation/Plan/ViewController/PlanViewController.swift
  travelPlan/travelPlan.xcodeproj/project.pbxproj
Labels: 🍣 Fix
